### ISSUE TITLE
Exception on Mac OS

### ISSUE THREAD

**Issue by jakedowns** [reasonml-editor/reasonml-idea-plugin#11]
> Mac OS Seirra 10.12.5
> Opam 1.2.2
> ReasonML Language Plugin Version: 0.19
> ocamlmerlin version 2.5.4
> Ocaml 4.02.3
> ocamlmerlin-reason version 0.1

> IntelliJ IDEA 2016.1.2
> Build #IU-145.971, built on April 29, 2016
> JRE: 1.8.0_76-release-b162 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

✅ added VM options
```
-DreasonBsb=node_modules/bs-platform/bin/bsb.exe
-DreasonMerlin=/usr/local/bin/opam/bin/ocamlmerlin
-DreasonRefmt=/usr/local/bin/opam/bin/refmt
-DreasonReformatOnSave=true
```

Getting:

```
Plugin 'reasonml' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.AbstractMethodError: com.reason.merlin.MerlinServiceComponent.disposeComponent()V
    at com.reason.merlin.MerlinServiceComponent.initComponent(MerlinServiceComponent.java:45)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:522)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
    at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:92)
    at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:500)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:516)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:458)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:450)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:61)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Any ideas here?

**Comment by jakedowns** [comment]
derp. merlin 3.0.2 failed to install due to an error with `install jbuilder 1.0+beta13`
