### ISSUE TITLE
Java exception when enabling the plugin

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#16]
I get an exception when I try to enable the plugin.  I'm using IntelliJ 15.0.2 on Windows.  Note that IntelliJ prompted me to enable the plugin.  What version are you working with?

I'm looking for a good development environment for OCaml.  Syntax support is good, but I'm especially keen to be able to navigate among definitions in the code.  If there's a reasonable path to get there, I would consider working on the project to get it.

```
Plugin 'reasonml' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoSuchMethodError: com.intellij.notification.Notification.<init>(Ljava/lang/String;Ljavax/swing/Icon;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/intellij/notification/NotificationType;Lcom/intellij/notification/NotificationListener;)V
    at com.reason.ide.RmlNotification.<init>(RmlNotification.java:19)
    at com.reason.merlin.MerlinProcess3.version(MerlinProcess3.java:42)
    at com.reason.merlin.MerlinServiceComponent.selectVersion(MerlinServiceComponent.java:61)
    at com.reason.merlin.MerlinServiceComponent.initComponent(MerlinServiceComponent.java:42)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:518)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
    at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:90)
    at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:496)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:505)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:454)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:446)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:60)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by giraud** [comment]
I'm sorry, this is a mistake. The SDK and the build ranges are not correctly synchronised. 
I will produce a new plugin version that should work with idea 15. 
But I'm not sure I'll be able to keep that compatibility in the future.

**Comment by giraud** [comment]
About navigating between elements, there is a clear path and I am working on it right now. I'm progressing slowly because I need to understand how PSI and indexing works in idea, but I'm making good progress.

The path is : 
- get correct PSI structures from parser
- get PSI indexing/stubs working
- implements PSIReference

After that, all features like Find usages, go to definition or renaming will be working.
But I'm not sure that it can be called a "reasonable" path :)

As for help, if you know idea internals, let me know. If not, send me the project you're working on and use cases you need most, or fill that project with issues :)

just know that I don't have a lot of time, so the project is moving forward slowly. Also, reason is my main target, and ocaml will be implemented after

**Comment by giraud** [comment]
Did you try this plugin ? https://github.com/sidharthkuruvila/ocaml-ide
it might be a better option for ocaml editing.

**Comment by jfehrle** [comment]
I have a friend (a former co-worker) who was on a team that implemented IntelliJ support for a proprietary language at my previous company just a year or two ago.  Perhaps he would be willing to answer your questions.  I will ask him.

What versions does the plugin support at the moment?  I could try it using the free edition of IntelliJ.

> send me the project you're working on

I want to use IntelliJ to make improvements to Coq (https://coq.inria.fr/).  At this point I'm trying to understand the code, which involves reading a lot of code and navigating in it.  And I'm OCAML beginner.

> send me the ... use cases you need most, or fill that project with issues :)

How about if I post that list as another issue on this project?

**Comment by jfehrle** [comment]
Let me check out the other plugin you mention before I ask my friend for help.

How is your plugin different from the other one?  There's no way, no desire for you guys to work together?  Multiple developers seems like it could make for a better plugin faster.

**Comment by giraud** [comment]
> How is your plugin different from the other one?

I wanted to have a plugin dedicated to reason and that's why I created one called reasonml, not ocaml.
Then I realise that I still need ocaml support and that people are asking for it. 

The 2 projects are taking different orientations, technically. I am moving away from merlin and trying to use the most of intellij internals mechanisms. Now, I would say they have incompatible implementations, and different goals.

**Comment by giraud** [comment]
> What versions does the plugin support at the moment?

It should be ok with idea 15

**Comment by giraud** [comment]
> How about if I post that list as another issue on this project?

Sure, I might know most of them, but it'll keep me motivated :)

**Comment by jfehrle** [comment]
I tried the updated plugin, which works fine, thanks.

What is reason?  I wasn't able to find anything about it on the web.

**Comment by giraud** [comment]
> What is reason?

Reason is a new syntax for the OCaml language. You can find information if you search for reasonML. The official website is https://reasonml.github.io/

It is driven by the guys from facebook and they're doing an awesome work to bring JS developers to the world of Ocaml. If you want to know more, the discord channel is the place to go.

**Comment by jfehrle** [comment]
Is reason a superset of OCaml, or is it (somewhat) incompatible?  If they're different, could a parser flag indicate which one it is parsing?  Or would separate parsers be needed?

I could ask my friend how much work it would take to get the semantic support for the languages into IJ.  If it's not too much, I would be willing to do some of it, focusing on OCaml.

Is there a branch for your work-in-progress?  What the issues you want to figure out next?

**Comment by giraud** [comment]
> Is reason a superset of OCaml, or is it (somewhat) incompatible? If they're different, could a parser flag indicate which one it is parsing? Or would separate parsers be needed?

Reason is just an alternate syntax, it generates the same AST than any OCaml source code. 
For idea plugin all the PSI elements and implemented features are the same for the two languages, but I need to implement two different parsers.

**Comment by giraud** [comment]
> I could ask my friend how much work it would take to get the semantic support for the languages into IJ. If it's not too much, I would be willing to do some of it, focusing on OCaml.

I'm not trying to get all semantics into IJ because in fact I'm relaying on Bucklescript to compile the code and validate the AST. So I need to work in a relaxed mode and accept potentially incorrect AST nodes.

For that I'm writing the parser by hand and trying to only pick the relevant (minimal) information from the lexer. I was using grammar-kit at the beginning but it's too rigid and complex for my needs. 

There is no branch, all code is here, in this repo, in master branch. you can have a look at it.
