### ISSUE TITLE
Can't find Bsb

### ISSUE THREAD

**Issue by d-s-d** [reasonml-editor/reasonml-idea-plugin#168]
plugin version: 0.76.1
OS: OS x 10.14.4
Intellij Version: 2019.1.1 CE

### Description

After updating to the latest available release (0.76.1), the plugin cannot find bsb anymore. bs-platform is installed globally *and* locally (i.e. in the project directory under nodes_modules/bs-platform).

The error message is:
```
    reason: Bsb: Can't find bsb.
      Working directory is '<project_dir>'.
      Be sure that bsb is installed and reachable from that directory, see github.
```

(rem: `<project_dir>` is the correct project directory).

**Comment by Coobaha** [comment]
cc @giraud

**Comment by nickmarca** [comment]
same here =p

**Comment by giraud** [comment]
sorry guys, 0.76.2 to the rescue !

**Comment by doombu** [comment]
@giraud have the same error with 0.76.2

**Comment by d-s-d** [comment]
the issue disappeared after updating to 0.76.2 in my case.
plugin version: 0.76.2
OS: OS x 10.14.4
Intellij Version: 2019.1.1 CE

**Comment by giraud** [comment]
@doombu more info ?

**Comment by doombu** [comment]
right, I've checked again and I have other case - I use yarn workspaces and `bs-platform` is installed at `packages/node_modules` and my project is in `packages/my-project`.
but at WebStorm config all paths are filled correctly:
![image](https://user-images.githubusercontent.com/1798527/56790029-f7b68480-6835-11e9-8ddd-8ac6e2a081ce.png)

**Comment by peterpme** [comment]
👍 also getting this - could be b/c we have the wrong versions of bs-platform installed?

**Comment by giraud** [comment]
no, it's because I screwed up. I totally forgot that option.
I'll try to fix it this week end.

**Comment by peterpme** [comment]
thank you @giraud you are an amazing person :smile:

**Comment by giraud** [comment]
@peterpme thanks ! 😃

**Comment by giraud** [comment]
I hope this bad experience is behind us with the release of 0.76.3.

**Comment by doombu** [comment]
@giraud sorry to tell it but has the same error message with 0.76.3 :(

**Comment by Coobaha** [comment]
Works now for me. In 0.76.2 I ha problem with multiple bs-platform projects in one repo. But it doesn't use yarn workspaces, just a multiple node_modules.

**Comment by Coobaha** [comment]
@doombu In the latest release yarn workspaces monorepo support was improved. Plugin looks for local `node_modules/.bin/bsb` now, so build/refmt works like they should. Don't forget to remove `bs-platform` location from plugin settings

**Comment by jongbelegen** [comment]
On the new version i get the following error after changing some code and saving it:
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'line' of com/reason/build/bs/compiler/BsProcess.ocamlVersionExtractor must not be null
	at com.reason.build.bs.compiler.BsProcess.$$$reportNull$$$0(BsProcess.java)
	at com.reason.build.bs.compiler.BsProcess.ocamlVersionExtractor(BsProcess.java)
	at com.reason.build.bs.compiler.BsProcess.getOCamlVersion(BsProcess.java:189)
	at com.reason.hints.InsightManagerImpl.getRincewindFilename(InsightManagerImpl.java:76)
	at com.reason.hints.InsightManagerImpl.getRincewindFile(InsightManagerImpl.java:60)
	at com.reason.hints.InsightManagerImpl.queryTypes(InsightManagerImpl.java:83)
	at com.reason.ide.hints.InferredTypesService.queryForSelectedTextEditor(InferredTypesService.java:65)
	at com.reason.build.bs.compiler.BsOutputListener.lambda$processTerminated$0(BsOutputListener.java:79)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

System:
```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,1
  Processor Name:	Intel Core i5
  Processor Speed:	2,3 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB

  System Version:	macOS 10.14.5 (18F132)
  Kernel Version:	Darwin 18.6.0
```

**Comment by giraud** [comment]
please, create issue instead
