### ISSUE TITLE
NoClassDefFoundError on Linux Mint

### ISSUE THREAD

**Issue by hoichi** [reasonml-editor/reasonml-idea-plugin#173]
plugin version: 0.78.1

bsb version: 5.0.4

```
WebStorm 2019.1.3
Build #WS-191.7479.14, built on May 27, 2019
JRE: 1.8.0_202-release-1483-b53 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-42-generic
```
### Description

Don’t let the timing of my report confuse you, that error wasn’t introduced by the last update. At least I was getting errors like this before. 

I haven’t figured out how to reproduce it consistently, but it does occur pretty often.

Also, I use the Material Theme UI plugin. Maybe it does interfere.

```
java.lang.NoClassDefFoundError: com/intellij/codeInsight/daemon/impl/GutterIconTooltipHelper
	at com.reason.ide.go.ORLineMarkerProvider.extractRelatedExpressions(ORLineMarkerProvider.java:70)
	at com.reason.ide.go.ORLineMarkerProvider.collectNavigationMarkers(ORLineMarkerProvider.java:48)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:48)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:40)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:194)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:96)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: com.intellij.codeInsight.daemon.impl.GutterIconTooltipHelper PluginClassLoader[reasonml, 0.78.1] com.intellij.ide.plugins.cl.PluginClassLoader@15172099
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more
```

**Comment by giraud** [comment]
I will check with webstorm.

**Comment by giraud** [comment]
Did you try without material theme ? I don't think it's linked, but...

**Comment by giraud** [comment]
Same on windows with fresh install

**Comment by hoichi** [comment]
I don’t know, maybe it did take longer this time, but the error still occurs with the Material UI plugin disabled.

**Comment by giraud** [comment]
Fixed in 0.78.2.
I had to remove the gutter icon functionality for Webstorm product. It's available only for java-based IDE.

**Comment by hoichi** [comment]
Awesome, thanks!

I have All Products license, but I only use ReasonML for the web, and I tend to prefer WebStorm because it’s better tuned for the web stack out of the box.

**Comment by hoichi** [comment]
Oh yeah, but having said that, WebStorm _does_ have some gutter icons.
![image](https://user-images.githubusercontent.com/3592345/60591536-57d22580-9da7-11e9-9ca3-77a8fc98e981.png)
Maybe it just has different API for them.

**Comment by giraud** [comment]
Strange !
