### ISSUE TITLE
Code reformatting stopped working after newest update

### ISSUE THREAD

**Issue by ktrzos** [reasonml-editor/reasonml-idea-plugin#202]
I've installed version 0.84-2019.3 on two machines and on both of them the reformatting on save stopped working.

**Comment by giraud** [comment]
Hi, can you add `ReasonML.refmt` in `Help` | `Debug log settings` and copy some of the logs ?

**Comment by ktrzos** [comment]
@giraud 
Should I search for any particular entries in the log file?
Only thing, which I found with "ReasonML" keyword was:

```
2019-12-17 07:53:58,207 [   3146]   INFO - lij.diagnostic.DebugLogManager - Set DEBUG for the following categories: ReasonML.refmt 
```

I changed/saved `*.re` file, and after that no additional logs.

Also, after restarting IDE and changing file tab, I got this exception (but I don't think that it is somehow related with this issue):

```
2019-12-17 08:03:48,947 [  48019]   INFO - notification.NotificationGroup - Notification group Profiling is already registered 
java.lang.Throwable
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:67)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:52)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:45)
	at com.intellij.ide.plugins.DynamicPlugins.<clinit>(DynamicPlugins.kt:53)
	at com.intellij.codeInsight.intention.impl.IntentionHintComponent.<init>(IntentionHintComponent.java:366)
	at com.intellij.codeInsight.intention.impl.IntentionHintComponent.showIntentionHint(IntentionHintComponent.java:135)
	at com.intellij.codeInsight.daemon.impl.IntentionsUIImpl.update(IntentionsUIImpl.java:52)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doApplyInformationToEditor(ShowIntentionsPass.java:237)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.applyInformationToEditor(TextEditorHighlightingPass.java:100)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService.lambda$applyInformationToEditorsLater$3(PassExecutorService.java:498)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by giraud** [comment]
do you have setting enabled ? File|settings|Languages|Reason

**Comment by ktrzos** [comment]
@giraud 
Yes, of course. I was using it before plugin update and it was working without any problem. I even turned it off and on to see if it will work again, but without success.

**Comment by giraud** [comment]
can you reformat manually  by using the menu `Code | Reformat code (refmt)` ?

**Comment by ktrzos** [comment]
@giraud 
Yes, I can. So manual reformatting is working, but somehow not on file save.

**Comment by giraud** [comment]
found the problem

**Comment by giraud** [comment]
you can try this beta version https://bintray.com/giraud/idea-plugin/download_file?file_path=reasonml-idea-plugin-0.85-beta13-2019.3.zip until a new release is published

**Comment by ktrzos** [comment]
I've checked this beta version by loading the whole ZIP file with "Install Plugin from Disk..." option. Reformatting stopped working at all. Even manual reformat does not work. Got this log:

> ReasonML.refmt.auto - Before document saving (Leon, autoSave=true) 
> ReasonML.refmt - No refmt binary found, reformat cancelled

**Comment by pulkitkkr** [comment]
I'm also having this issue on jetbrains version `2019.3`

**Comment by giraud** [comment]
can you try refmt with 0.85-2019.3 ?

**Comment by ktrzos** [comment]
@giraud 

Checked version _0.85-2019.3_.
Now I got this error:

```
reason: Reason
Can't download /home/user/.PhpStorm2019.3/config/plugins/reasonml-plugin-idea/rincewind_l4.02.3-0.6.exe
java.io.FileNotFoundException: https://dl.bintray.com/giraud/ocaml/rincewind_l4.02.3-0.6.exe
```

Formatting it not working at all. Every time, when I want to save file, above error appears.

**Comment by ktrzos** [comment]
@giraud 
Sorry, autoformatting is working fine with _0.85-2019.3_, but error still appears.

**Comment by giraud** [comment]
pushed missing files to bintray. should be good
