### ISSUE TITLE
Exception:  Write access is allowed from event dispatch thread only

### ISSUE THREAD

**Issue by daharon** [reasonml-editor/reasonml-idea-plugin#207]
Plugin version: 
`0.84-2019.3`

### Description
I'm seeing the following error when trying to use the ReasonML plugin with OCaml:
```
Write access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@61cde97b
Current thread: Thread[Updating Indices,4,Idea Thread Group] 1199364144
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 353002692
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:959)
	at com.intellij.openapi.application.impl.ApplicationImpl.startWrite(ApplicationImpl.java:1041)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:883)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl$MyRootProvider.rootsChanged(ProjectJdkImpl.java:285)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.copyTo(ProjectJdkImpl.java:266)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.commitChanges(ProjectJdkImpl.java:303)
	at com.reason.OCamlSdkType.reindexSourceRoots(OCamlSdkType.java:114)
	at com.reason.ide.ORProjectRootListener$1$1.performInDumbMode(ORProjectRootListener.java:41)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runSingleTask$9(DumbServiceImpl.java:593)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.project.DumbServiceImpl.runSingleTask(DumbServiceImpl.java:586)
	at com.intellij.openapi.project.DumbServiceImpl.runBackgroundProcess(DumbServiceImpl.java:563)
	at com.intellij.openapi.project.DumbServiceImpl.access$400(DumbServiceImpl.java:57)
	at com.intellij.openapi.project.DumbServiceImpl$4.run(DumbServiceImpl.java:517)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Some more details from the log:
```
2020-01-19 09:51:41,678 [ 802147]  ERROR - penapi.project.DumbServiceImpl - IntelliJ IDEA 2019.3.1  Build #IU-193.5662.53 
2020-01-19 09:51:41,678 [ 802147]  ERROR - penapi.project.DumbServiceImpl - JDK: 11.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-01-19 09:51:41,678 [ 802147]  ERROR - penapi.project.DumbServiceImpl - OS: Linux 
2020-01-19 09:51:41,683 [ 802152]  ERROR - penapi.project.DumbServiceImpl - Plugin to blame: ReasonML version: 0.84-2019.3 
2020-01-19 09:51:41,683 [ 802152]  ERROR - penapi.project.DumbServiceImpl - Last Action: ShowProjectStructureSettings 
```

**Comment by daharon** [comment]
On further inspection it appears that this was already fixed in commit 3bf10c4.
I'll just wait for the next release.
