### ISSUE TITLE
IntelliJ error "Assertion failed: Too many element types registered. Out of (short) range."

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#28]
I just noticed this exception in IntelliJ.  It's happened 81 times, last time on Jan 1.  I'm working with the Coq source code, which is quite large.

![image](https://user-images.githubusercontent.com/1253341/34750150-4b67f848-f55a-11e7-8e18-6964a95852ce.png)

```
Assertion failed: Too many element types registered. Out of (short) range.
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.psi.tree.IElementType.<init>(IElementType.java:104)
	at com.intellij.psi.tree.IElementType.<init>(IElementType.java:88)
	at com.reason.lang.CommonParser.<init>(CommonParser.java:20)
	at com.reason.lang.ocaml.OclParser.<init>(OclParser.java:18)
	at com.reason.lang.ocaml.OclParserDefinition.createParser(OclParserDefinition.java:50)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:87)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:240)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:39)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.isReplaceWholeNode(BlockSupportImpl.java:331)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:277)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.makeFullParse(BlockSupportImpl.java:216)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:92)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:752)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$commitUnderProgress$4(DocumentCommitThread.java:533)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1148)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:558)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$pollQueue$1(DocumentCommitThread.java:375)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.psi.impl.DocumentCommitThread.pollQueue(DocumentCommitThread.java:375)
	at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:326)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by giraud** [comment]
when does it happen ? when you open a file in particular ?
which version of idea ? are you using a recent (2017) one ?

**Comment by giraud** [comment]
I hope it is fixed in 0.34.
I will let this issue open a few days. If you don't see the assertion again during that period, I'll close the bug then.

**Comment by jfehrle** [comment]
I'm using the Community Edition 2017.2.5.

I don't know what is triggering it.  IntelliJ doesn't make it easy to notice these: exceptions are logged but all the user sees is a tiny red icon is the lower right hand corner of the IJ screen.  So alas, I'm almost guaranteed not to notice it right away.  I'll let you know if I see more exceptions.

Thanks.

**Comment by giraud** [comment]
@jfehrle did it happen again ?

**Comment by jfehrle** [comment]
No, I've not seen this error since you made your changes.
Jim
