### ISSUE TITLE
Plugin causes project indexing to fail on reading of file

### ISSUE THREAD

**Issue by williamtdr** [reasonml-editor/reasonml-idea-plugin#42]
Plugin version: 0.43

### Description
The plugin causes an internal exception in IDEA when indexing the following file - causing subsequent indexing to fail and thus project files to not be editable. I've included the source code of the offending file as well as the stack trace IDEA provides. Happy to try things in order to help debug this.

### Code
```
let all_evens =
	List.filter (fun x -> x mod 2 = 0)

let increment_all =
	List.map (fun x -> x + 1)

let max_fold =
	List.fold_left (fun x y -> if x > y then x else y) (-max_int)

let sum_prod =
	List.fold_left (fun (sum, prod) x -> (sum + x, prod * x)) (0, 1)

let split f list =
  let accum = ([], []) in
  let (lsts, curr) = List.fold_left (fun (sublists, current) x -> if (f x)
								     then (List.rev current :: sublists, [])
									 else (sublists, x :: current)) accum list
  in List.rev (List.rev curr :: lsts)
```

### Stack Trace
```
Error while indexing /Users/williamtdr/GitHub/csci2041/public-class-repo/Sample Programs/Sec_10_3-35pm/Intervals/v4/useInterval.ml
To reindex this file IDEA has to be restarted: com.reason.lang.core.psi.impl.PsiFileModuleImpl.getGreenStub()Lcom/intellij/psi/stubs/StubElement;
java.lang.NoSuchMethodError: com.reason.lang.core.psi.impl.PsiFileModuleImpl.getGreenStub()Lcom/intellij/psi/stubs/StubElement;
	at com.reason.lang.core.psi.impl.PsiFileModuleImpl.getQualifiedName(PsiFileModuleImpl.java:103)
	at com.reason.lang.core.psi.impl.PsiFileModuleImpl.getName(PsiFileModuleImpl.java:97)
	at com.reason.lang.core.stub.type.ModuleStubElementType.createStub(ModuleStubElementType.java:32)
	at com.reason.lang.core.stub.type.ModuleStubElementType.createStub(ModuleStubElementType.java:19)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:74)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:36)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:86)
	at com.intellij.psi.stubs.StubUpdatingIndex$4.a(StubUpdatingIndex.java:209)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:851)
	at com.intellij.psi.stubs.StubUpdatingIndex$4.map(StubUpdatingIndex.java:208)
	at com.intellij.psi.stubs.StubUpdatingIndex$4.map(StubUpdatingIndex.java:191)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:457)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1633)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1559)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:505)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1516)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1501)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:107)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:219)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1034)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:236)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by giraud** [comment]
Thanks for taking the time to produce the detailed report, it really helps.

I tried the source code locally but I don't get the stack trace.
The stub should be created when idea creates the index, and the code has nothing special that would make the indexing fail. Can you invalidate the caches and restart idea (menu `file | Invalidate caches / restart`) ?

**Comment by williamtdr** [comment]
Hello @giraud!

I followed your suggestion and invalidated caches - all good now! I did try that before, but I also updated IDEA this time. Perhaps either a batched update process, or maybe the plugin was depending on something that wasn't in the old version. I have preference folders for 2016.2 and 2017.3 in ~/Library/Preferences.

**Comment by giraud** [comment]
clearly something went wrong with indexes. I can't do anything else, I'm closing that issue
